services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    ports:
      - "${BACKEND_PORT:-8001}:8001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=trinity
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=trinity
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/database:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
