# Charger les propriétés depuis le fichier .env
# Nota : Ces propriétés seront remplacées par les valeurs d'environnement en CI/CD

# Propriétés du projet
sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.projectName=${env.SONAR_PROJECT_NAME}
sonar.projectVersion=${env.SONAR_PROJECT_VERSION}
sonar.qualitygate.wait=true

# Configuration du serveur SonarQube
sonar.host.url=${env.SONAR_HOST_URL}

# Authentification (utilisera les variables d'environnement SONAR_LOGIN et SONAR_PASSWORD)
# Ne pas mettre directement les identifiants ici

sonar.sourceEncoding=UTF-8
