sonar.projectKey=PAR_26_T-DEV-702-Api_AZTvSC9LEkXlCD2jMUfC
sonar.projectName=T-DEV-702-Api
sonar.projectVersion=1.0
sonar.qualitygate.wait=true

sonar.host.url=http://89.156.15.147:9000

sonar.login=admin
sonar.password=nathan

sonar.sourceEncoding=UTF-8
